appName: idurar-erp-crm
appUniqueId: ravis/idurar-erp-crm
appInfo:
  description: this is crm app
  appVersion: 1.0.0
  appRepoUrl: https://github.com/rawatSingh2022/crm-demo.git
  appIconUrl: ''
  appAuthorUserId: ravis
  forkedFrom: ''
technicalInfo:
  supportedLanguages:
    - react
    - nodejs
  supportedFrameworks:
    - react
    - express
  secrets: []
  services:
    - node
  knowledgebases: []
  instruction: []
usage:
  develop:
    agents: []
    layout: ''
    run:
      - shell:
          command: cd backend && npm start
      - shell:
          command: cd frontend && npm run dev
  install:
    steps:
      - command:
          type: shell
          description: install backend packages
          command: cd backend && npm install
      - command:
          type: shell
          description: install frontend packages
          command: cd frontend && npm install
    customInstallationAgent:
      agent: ''
      enabled: false
  appUse:
    agents: []
    layout: ''
    prerunsteps: null
    appPreview:
      type: ''
