appName: idurar-erp-crm/ravis
appUniqueId: ravis/idurar-erp-crm
appInfo:
  description: this is crm app
  appVersion: 1.0.0
  appRepoUrl: ''
  appIconUrl: ''
  appAuthorUserId: ravis
  forkedFrom: ''
technicalInfo:
  supportedLanguages:
    - react
    - nodejs
  supportedFrameworks:
    - react
    - express
  secrets: []
  services:
    - node
  knowledgebases: []
  instruction: []
usage:
  develop:
    agents: []
    layout: ''
    run:
  install:
    steps: []
    customInstallationAgent:
      agent: ''
      enabled: false
  appUse:
    agents: []
    layout: ''
    prerunsteps:
    appPreview:
      type: ''
